### ISSUE TITLE
ifNil and isNil ifTrue have different behaviour on ForeignNil TruffleObjects

### ISSUE THREAD

**Issue by Kolpa** [hpi-swa/trufflesqueak#100]
Calling `foreginNilValue isNil ifTrue: [^'isNil']` works as expected and will return the `isNil` string.
Calling `foreginNilValue ifNil: [^'isNil']` will return the original `ForeginNil` object instead.

This is caused by the squeak compiler which produces an identity check on `ifNil` but not on `isNil ifTrue`.

**Comment by fniephaus** [comment]
if(Not)Nil... methods are dropped from ForeignObject for now.

**Comment by fniephaus** [comment]
The problem here is that nil values from different languages should probably not be identical. Otherwise, there's no way to distinguish between Smalltalk `nil`, Java `null`, and Python `None`. Moreover, Javascript and other languages may have multiple nil-like values. Graal.js, for example, exposes both `null` and `undefined` as null values. I can't think of a better solution than using `foreignNilValue isNil ifTrue: [...] ifFalse: [...]` for now.
