### ISSUE TITLE
Inspecting a Java Array does not show the array elements

### ISSUE THREAD

**Issue by janehmueller** [hpi-swa/trufflesqueak#137]
When inspecting a Java Array (e.g., `object getClass getMethods`) the Inspector does not show the array elements, but it does show the size of the array:
![image](https://user-images.githubusercontent.com/12008040/112046390-436e2780-8b4c-11eb-9cc2-dc3097ec7800.png)

Using `self polyglotInspect` does not resolve this issue.

**Comment by fniephaus** [comment]
Turns out this happens because @janehmueller was using an older Squeak image without the new Inspector APIs. Updating the image should fix this problem. Note that until 21.0.0.1, TruffleSqueak used a Squeak 5.3 image as base. I've upgraded the base image to a recent trunk image (see [here](https://github.com/hpi-swa/trufflesqueak/releases/download/21.0.0.1/TruffleSqueakImage-21.1.0-dev.zip)).
